apiVersion: v1
kind: Namespace
metadata:
  name: kafka
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: kafka-connect-ui
  namespace: kafka
  labels:
    app: kafka-connect-ui
spec:
  replicas: 1
  selector:
    matchLabels:
      app: kafka-connect-ui
  template:
    metadata:
      labels:
        app: kafka-connect-ui
    spec:
      containers:
        - name: kafka-connect-ui
          image: landoop/kafka-connect-ui
          ports:
            - containerPort: 8000
          env:
            - name: CONNECT_URL
              value: http://kafka-connect:8083  
          resources:
            limits:
              memory: "256Mi"
              cpu: "250m"
---
apiVersion: v1
kind: Service
metadata:
  name: kafka-connect-ui
  namespace: kafka
  labels:
    app: kafka-connect-ui
spec:
  type: NodePort
  selector:
    app: kafka-connect-ui
  ports:
    - name: http
      port: 80
      targetPort: 8000
      nodePort: 30086
