kind: Cluster
apiVersion: kind.x-k8s.io/v1alpha4
nodes:
- role: control-plane
  extraPortMappings:
  - containerPort: 30080
    hostPort: 8080
    protocol: TCP
  - containerPort: 30081
    hostPort: 8081
    protocol: TCP
  - containerPort: 30082
    hostPort: 8082
    protocol: TCP
  - containerPort: 30083
    hostPort: 8083
    protocol: TCP
  - containerPort: 30084
    hostPort: 8084
    protocol: TCP
  - containerPort: 30085
    hostPort: 8085
    protocol: TCP
  - containerPort: 30086
    hostPort: 8086
    protocol: TCP
  - containerPort: 30777
    hostPort: 9000
    protocol: TCP
  - containerPort: 30092
    hostPort: 9092
    protocol: TCP
  - containerPort: 30021
    hostPort: 9021
    protocol: TCP
  - containerPort: 80
    hostPort: 80
    protocol: TCP
  - containerPort: 443
    hostPort: 443
    protocol: TCP
